Bump example version for Cargo.toml dep
Before this commit, following the documentation's example gave a compile
error because the `use` expression for the `Command` struct wasn't compatible with this crate's `0.11` version.

This is the error using `0.11` produces:

```
error[E0432]: unresolved import `assert_cmd::Command`
 --> tests/tests.rs:2:5
  |
2 | use assert_cmd::Command;
  |     ^^^^^^^^^^^^^^^^^^^ no `Command` in the root
```

After this commit, the `use` expression is compatible with the crate.